version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www
    links:
      - "localstack:my-bucket.s3.localhost.localstack.cloud"
    depends_on:
      - localstack
  nginx:
    image: nginx
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - 80:80
        
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_project
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d

  node:
    image: node:12-alpine
    tty: true
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    entrypoint: npm run watch
    ports:
      - 3000:3000

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis

  localstack:
    image: localstack/localstack:latest
    environment:
        - SERVICES=s3,lambda,sqs,dynamodb
        - DEFAULT_REGION=ap-northeast-1
        - DATA_DIR=/tmp/localstack/data
    volumes:
        - localstack-tmp:/tmp/localstack
        - localstack-aws:/root/.aws
        - './docker/localstack:/docker-entrypoint-initaws.d/make-s3.sh'
volumes:
  localstack-tmp:
    driver: local
  localstack-aws:
    driver: local